[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd backend && npm install && npx prisma generate && npx prisma migrate deploy && npm run build"]

[start]
cmd = "cd backend && node dist/index.js"
