[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd backend && npm install && ./node_modules/.bin/prisma generate && ./node_modules/.bin/prisma migrate deploy && npm run build"]

[start]
cmd = "cd backend && node dist/index.js"
